### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by JessitaMS** [jamescalam/jamescalam#1]
Hello James:

First, congratulate you for the great work you do, you explain all the concepts very well. I had nowhere to write about "How to Build a Bert WordPiece Tokenizer in Python and HuggingFace", so I went to the first git I found. 

I'm very new to NLP, so I have existential doubts...lol...one of them is, once we download datasets, in this case OSCAR, it probably takes up a total of aprox 200GB if after I finish working With it I want to remove it so that it does not take up space, where should I look to do this process? At the moment all the videos I see talk about downloading datasets but not about removing them later???

Regards

**Comment by jamescalam** [comment]
Hey Jessita, thanks I'm happy to hear it helps! Unfortunately the existential doubts won't go away with more experience 😅

For deleting the datasets you can find them in you user directory under `~/.cache/huggingface/datasets`, you can delete the directories there to clear the downloaded datasets.

Does that solve your problem?

**Comment by JessitaMS** [comment]
Hello James, 

yes your answer has solved my doubt. Thank you very much for the prompt feedback, I really appreciate it.

Regards

**Comment by jamescalam** [comment]
You're welcome!

**Comment by JessitaMS** [comment]
Hello James,

New questions lol. The tokenizer that you teach how to do in the video is great for me if I want to load a previously trained BERT Tokenizer (correct me if I'm wrong). But what if I want to use that tokenization in the transformers pipeline. I have tried to do this and am getting an error as it cannot instantiate the pipeline with the specified tokenizer.
So my question is: am I missing some other step? I think that from what I've been reading, I'm missing a config.json file, right? (how can I do this?)

Thank you very much,

Regards
